[2025-02-09T15:24:48.014+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T15:24:48.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_postgres.wait_for_extract_postgres manual__2025-02-09T15:24:44.347124+00:00 [queued]>
[2025-02-09T15:24:48.055+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_postgres.wait_for_extract_postgres manual__2025-02-09T15:24:44.347124+00:00 [queued]>
[2025-02-09T15:24:48.057+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-09T15:24:48.082+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_extract_postgres> on 2025-02-09 15:24:44.347124+00:00
[2025-02-09T15:24:48.094+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2194) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T15:24:48.097+0000] {standard_task_runner.py:72} INFO - Started process 2196 to run task
[2025-02-09T15:24:48.098+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_postgres', 'wait_for_extract_postgres', 'manual__2025-02-09T15:24:44.347124+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/Load_CSV_to_Postgres.py', '--cfg-path', '/tmp/tmp3e_b1eqz']
[2025-02-09T15:24:48.100+0000] {standard_task_runner.py:105} INFO - Job 139: Subtask wait_for_extract_postgres
[2025-02-09T15:24:48.174+0000] {task_command.py:467} INFO - Running <TaskInstance: load_csv_to_postgres.wait_for_extract_postgres manual__2025-02-09T15:24:44.347124+00:00 [running]> on host 8c410daec8d3
[2025-02-09T15:24:48.637+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T15:24:44.347124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T15:24:44.347124+00:00'
[2025-02-09T15:24:48.640+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T15:24:48.641+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T15:24:48.642+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_extract_postgres state:running start_date:2025-02-09 15:24:48.044153+00:00
[2025-02-09T15:24:48.642+0000] {logging_mixin.py:190} INFO - Dag name:load_csv_to_postgres and current dag run status:running
[2025-02-09T15:24:48.644+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T15:24:48.644+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-09T15:24:48.645+0000] {external_task.py:258} INFO - Poking for tasks ['extract_postgres_data'] in dag extract_postgres_and_csv_data on 2025-02-09T15:24:44.347124+00:00 ... 
[2025-02-09T15:24:48.647+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-09T15:25:46.857+0000] {external_task.py:258} INFO - Poking for tasks ['extract_postgres_data'] in dag extract_postgres_and_csv_data on 2025-02-09T15:24:44.347124+00:00 ... 
[2025-02-09T15:26:18.889+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-09T15:26:18.891+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-09T15:26:18.895+0000] {process_utils.py:132} INFO - Sending 15 to group 2196. PIDs of all processes in the group: [2196]
[2025-02-09T15:26:18.896+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2196
[2025-02-09T15:26:18.897+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-09T15:26:18.933+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T15:26:18.991+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2196, status='terminated', exitcode=0, started='15:24:47') (2196) terminated with exit code 0
